<h3>Happy Customers</h3>

<h4>Project Goals</h4>

- Predict if a customer is happy or not based on the answers they give to questions asked.

- Reach 73% accuracy score or above, or convince why the solution is superior.

- Using a feature selection approach help to understand what is the minimal set of attributes/features that would preserve the most information about the problem while increasing predictability of the data we have. Is there any question that can be removed in the next survey?

<h4>Data Overview</h4>

- A dataset which includes responses from a short survey filled out by customers.
- Structure is as follows:

    **X1** = my order was delivered on time

    **X2** = contents of my order was as I expected

    **X3** = I ordered everything I wanted to order

    **X4** = I paid a good price for my order

    **X5** = I am satisfied with my courier

    **X6** = the app makes ordering easy for me

    **Y** = target attribute (Y) with values indicating 0 (unhappy) and 1 (happy) customers

    Attributes X1 to X6 indicate the responses for each question and have values from **1** to **5** where the smaller number indicates less and the higher number indicates more towards the answer.

In [7]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
raw_data = pd.read_csv("ACME-HappinessSurvey2020.csv")

<h4>Exploratory Data Analysis (EDA)</h4>

In [3]:
raw_data.head(10)

   Y  X1  X2  X3  X4  X5  X6
0  0   3   3   3   4   2   4
1  0   3   2   3   5   4   3
2  1   5   3   3   3   3   5
3  0   5   4   3   3   3   5
4  0   5   4   3   3   3   5
5  1   5   5   3   5   5   5
6  0   3   1   2   2   1   3
7  1   5   4   4   4   4   5
8  0   4   1   4   4   4   4
9  0   4   4   4   2   5   5

- X1 - X6 are the features.
- Y is the target.

Check datatypes:

In [4]:
raw_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Y       126 non-null    int64
 1   X1      126 non-null    int64
 2   X2      126 non-null    int64
 3   X3      126 non-null    int64
 4   X4      126 non-null    int64
 5   X5      126 non-null    int64
 6   X6      126 non-null    int64
dtypes: int64(7)
memory usage: 7.0 KB

Check for null/missing values (and remove accordingly):

In [5]:
raw_data.isnull().sum()
raw_data.isnull().mean().sort_values(ascending=False)

Y     0.0
X1    0.0
X2    0.0
X3    0.0
X4    0.0
X5    0.0
X6    0.0
dtype: float64

- Looks complete

Basic statistics of the dataset:

- Numerical:

In [6]:
raw_data.describe()

,Y,X1,X2,X3,X4,X5,X6
count,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000,126.000000
mean,0.547619,4.333333,2.531746,3.309524,3.746032,3.650794,4.253968
std,0.499714,0.800000,1.114892,1.023440,0.875776,1.147641,0.809311
min,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,0.000000,4.000000,2.000000,3.000000,3.000000,3.000000,4.000000
50%,1.000000,5.000000,3.000000,3.000000,4.000000,4.000000,4.000000
75%,1.000000,5.000000,3.000000,4.000000,4.000000,4.000000,5.000000
max,1.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000

- Visualised: